steps:
  - uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.10"

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Run Firestore sync script
    run: python sync_games.py
    env:
      IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
      IGDB_CLIENT_SECRET: ${{ secrets.IGDB_CLIENT_SECRET }}
      IGDB_ACCESS_TOKEN: ${{ secrets.IGDB_ACCESS_TOKEN }}
      FIRESTORE_PROJECT_ID: ${{ secrets.FIRESTORE_PROJECT_ID }}
