name: Firestore Sync

on:
  workflow_dispatch: # runs manually

permissions:
  contents: write # ✅ allow pushing changes

jobs:
  sync-games:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true # needed so we can push changes

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Firestore sync
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
          FIRESTORE_PROJECT_ID: ${{ secrets.FIRESTORE_PROJECT_ID }}
          IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
          IGDB_CLIENT_SECRET: ${{ secrets.IGDB_CLIENT_SECRET }}
          IGDB_ACCESS_TOKEN: ${{ secrets.IGDB_ACCESS_TOKEN }}
        run: python sync_games.py

      - name: Commit and push updated JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add games_backup.json
          git commit -m "Update games_backup.json from workflow" || echo "No changes to commit"
          git push
